Looks like a typo
rileytestut/AltStore pull request #553
Opened 2020-11-29 11:37 UTC by SaifurRahmanMohsin

Also, it would be nice to see some compilation instructions for AltServer coz this doesn't seem to compile.

2021-01-21 05:27 UTC, fylo5 approved these changes

2021-06-27 21:14 UTC, lonkle requested changes
This genuinely looks like a typo...but then @rileytestut - how have you been compiling this? Unless the typo in the filename is also somewhere in the project. In which case, I'd suggest to check that just in case.

Btw, @mohsin - I've personally never compiled AltServer for macOS actually, but I'll look into it and add a comment to this if I figure it out for ya and can help.

2021-06-27 22:17 UTC, lonkle commented
Did some digging. @mohsin - try this before building:

1. Using Homebrew: `brew install carthage`)
2. Then run `carthage update` in the root directory of the repo

Then build? Let me know if it works. 🤞

2021-09-14 19:28 UTC, ds8k commented
https://stackoverflow.com/questions/4562255/xcode-m-vs-mm

It probably isn't compiling because you need to update the reference inside the app. Regardless, this isn't wrong.

2023-01-24 22:52 UTC, closed without merging